version: '3.1'

services:

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
    - db
    restart: always
    command: sh -c "/wait && node sql/dbCreate.js && node app.js"
    networks:
      - iwa-net
    environment:
      - NODE_ENV=production
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    profiles: ["dev","test","production"]  

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    networks:
      - iwa-net
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - db
    networks:
      - iwa-net

  nginx-test:
    image: nginx:1.15-alpine
    depends_on:
    - app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    networks:
      - iwa-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    profiles: ["test"]

  nginx:
    image: nginx:1.15-alpine
    depends_on:
    - app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - iwa-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    profiles: ["production"]

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - iwa-net
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    profiles: ["production"]

networks:
  iwa-net:
